<p><span id="displaytitle" title=""></span></p> 
<table style="width:100%; border:solid 1px #71c837; background:#c6e9af; color:#2d5016;" class="noprint"> 
 <tbody> 
  <tr> 
   <td style="text-align:left; width:33%; font-size:90%;"><img alt="" src="//upload.wikimedia.org/wikibooks/en/thumb/d/df/Navigation_Left_Arrow.svg/18px-Navigation_Left_Arrow.svg.png" width="18" height="14" srcset="//upload.wikimedia.org/wikibooks/en/thumb/d/df/Navigation_Left_Arrow.svg/27px-Navigation_Left_Arrow.svg.png 1.5x, //upload.wikimedia.org/wikibooks/en/thumb/d/df/Navigation_Left_Arrow.svg/36px-Navigation_Left_Arrow.svg.png 2x" data-file-width="165" data-file-height="130"> <a href="/wiki/Java_Programming/Stack_trace" title="Java Programming/Stack trace">Stack trace</a></img></td> 
   <td style="text-align:center; width:34%;"><a href="/wiki/Java_Programming" title="Java Programming">Java Programming</a><br> <b>Nesting Exceptions</b></br></td> 
   <td style="text-align:right; width:33%; font-size:90%;"><a href="/wiki/Java_Programming/Concurrent_Programming" title="Java Programming/Concurrent Programming">Concurrent Programming</a> <img alt="" src="//upload.wikimedia.org/wikibooks/en/thumb/e/ea/Navigation_Right_Arrow.svg/18px-Navigation_Right_Arrow.svg.png" width="18" height="14" srcset="//upload.wikimedia.org/wikibooks/en/thumb/e/ea/Navigation_Right_Arrow.svg/27px-Navigation_Right_Arrow.svg.png 1.5x, //upload.wikimedia.org/wikibooks/en/thumb/e/ea/Navigation_Right_Arrow.svg/36px-Navigation_Right_Arrow.svg.png 2x" data-file-width="165" data-file-height="130" /></td> 
  </tr> 
 </tbody> 
</table> 
<p><br> When an exception is caught, the exception contains the <a href="/wiki/Java_Programming/Stack_trace" title="Java Programming/Stack trace">stack-trace</a>, which describes the error and shows where the exception happened, where the problem is, where the application programmer should look to fix the problem. Sometime it is desirable to catch an exception and throw another new exception. If the new exception keep a reference to the first exception, the first exception is called a <i>nesting exception</i>.</br></p> 
<table style="width: 100%;"> 
 <tbody> 
  <tr> 
   <td valign="top"> 
    <table style="padding:2px; margin:2px;"> 
     <tbody> 
      <tr valign="top"> 
       <td style="width:32px;"><img alt="Computer code" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/78/Gnome-settings-accessibility-keyboard.svg/32px-Gnome-settings-accessibility-keyboard.svg.png" title="Computer code" width="32" height="32" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/78/Gnome-settings-accessibility-keyboard.svg/48px-Gnome-settings-accessibility-keyboard.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/78/Gnome-settings-accessibility-keyboard.svg/64px-Gnome-settings-accessibility-keyboard.svg.png 2x" data-file-width="60" data-file-height="60" /></td> 
       <td style="background-color:#ffeee0; border-left: 4px solid orange; padding-left: 6px; font-family: Monaco, Consolas, 'Courier New', Courier; font-size:1.0em; line-height:1.5 !important;"><span id="code-listing-4"><b>Code listing 6.4: NestingExceptionExample.java</b></span> 
        <div class="mw-highlight mw-content-ltr" dir="ltr"> 
         <pre>
<span class="lineno"> 1 </span><span class="kd">public</span> <span class="kd">class</span> <span class="nc">NestingExceptionExample</span> <span class="o">{</span>
<span class="lineno"> 2 </span> 
<span class="lineno"> 3 </span>  <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="n">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="kd">throws</span> <span class="n">Exception</span> <span class="o">{</span>
<span class="lineno"> 4 </span>    <span class="n">Object</span><span class="o">[]</span> <span class="n">localArgs</span> <span class="o">=</span> <span class="o">(</span><span class="n">Object</span><span class="o">[])</span> <span class="n">args</span><span class="o">;</span>
<span class="lineno"> 5 </span>   
<span class="lineno"> 6 </span>    <span class="k">try</span> <span class="o">{</span>
<span class="lineno"> 7 </span>      <span class="n">Integer</span><span class="o">[]</span> <span class="n">numbers</span> <span class="o">=</span> <span class="o">(</span><span class="n">Integer</span><span class="o">[])</span> <span class="n">localArgs</span><span class="o">;</span>
<span class="lineno"> 8 </span>    <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="n">ClassCastException</span> <span class="n">originalException</span><span class="o">)</span> <span class="o">{</span>
<span class="lineno"> 9 </span><span class="hll">      <span class="n">Exception</span> <span class="n">generalException</span> <span class="o">=</span> <span class="k">new</span> <span class="n">Exception</span><span class="o">(</span>
</span><span class="lineno">10 </span><span class="hll">        <span class="s">"Horrible exception!"</span><span class="o">,</span>
</span><span class="lineno">11 </span><span class="hll">        <span class="n">originalException</span><span class="o">);</span>
</span><span class="lineno">12 </span><span class="hll">      <span class="k">throw</span> <span class="n">generalException</span><span class="o">;</span>
</span><span class="lineno">13 </span>    <span class="o">}</span>
<span class="lineno">14 </span>  <span class="o">}</span>
<span class="lineno">15 </span><span class="o">}</span>
</pre> 
        </div> </td> 
      </tr> 
     </tbody> 
    </table> </td> 
   <td valign="top"> 
    <table style="padding:2px; margin:2px; width:100%;"> 
     <tbody> 
      <tr valign="top"> 
       <td style="width:32px;"><img alt="Standard input or output" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Nuvola_apps_display.png/32px-Nuvola_apps_display.png" title="Standard input or output" width="32" height="32" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Nuvola_apps_display.png/48px-Nuvola_apps_display.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Nuvola_apps_display.png/64px-Nuvola_apps_display.png 2x" data-file-width="128" data-file-height="128" /></td> 
       <td style="background-color:#f0f0ff; border-left: 4px solid blue; padding-left: 6px; font-family: Monaco, Consolas, 'Courier New', Courier; font-size:1.0em; line-height:1.5 !important;"><b>Output for Code listing 6.4</b> <pre style="background-color:black; color:white;">
Exception in thread "main" java.lang.Exception: Horrible exception!
at NestingExceptionExample.main(NestingExceptionExample.java:9)
Caused by: java.lang.ClassCastException: [Ljava.lang.String; incompatible with [Ljava.lang.Integer;
at NestingExceptionExample.main(NestingExceptionExample.java:7)
</pre></td> 
      </tr> 
     </tbody> 
    </table> </td> 
  </tr> 
 </tbody> 
</table> 
<p>The above code is an example of a nesting exception. When the <code>Exception</code> is thrown, by passing in the <code>ClassCastException</code> object reference as a parameter, the <code>ClassCastException</code> is nested in the newly created <code>Exception</code>, its stack-trace is appended together. When the <code>Exception</code> is caught, its stack-trace contains the original <code>ClassCastException</code>'s stack-trace.</p> 
<p>This is a kind of exception conversion, from one exception to another. For example, calling a remote object using RMI, the calling method has to deal with <code>RemoteException</code> which is thrown if something is wrong during the communication. For the application point of view, <code>RemoteException</code> has no meaning, it should be transparent to the application that a remote object was used or not. So the <code>RemoteException</code> should be converted to an application exception.</p> 
<p>This conversion can also hide where the error is originated. The stack-trace starts when the exception is thrown. So when we catch and throw a new exception, the stack-trace starts at when the new exception was thrown, losing the original stack-trace. This was true with the earlier version of Java (before 1.4). Since then, a so called <i>cause facility</i> capabilities were built in the <code>Throwable</code> class.</p> 
<p>A throwable contains a snapshot of the execution stack of its thread at the time it was created. It can also contain a message string that gives more information about the error. Finally, it can contain a cause: another throwable that caused this throwable to get thrown. The cause facility is also known as the <i>chained exception facility</i>, as the cause can, itself, have a cause, and so on, leading to a "chain" of exceptions, each caused by another.</p> 
<p>A cause can be associated with a throwable in two ways: via a constructor that takes the cause as an argument, or via the <code>initCause(Throwable)</code> method. New throwable classes that wish to allow causes to be associated with them should provide constructors that take a cause and delegate (perhaps indirectly) to one of the <code>Throwable</code> constructors that takes a cause. For example:</p> 
<table style="padding:2px; margin:2px;"> 
 <tbody> 
  <tr valign="top"> 
   <td style="width:32px;"><img alt="Example" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Nuvola_apps_edu_miscellaneous.svg/32px-Nuvola_apps_edu_miscellaneous.svg.png" title="Example" width="32" height="32" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Nuvola_apps_edu_miscellaneous.svg/48px-Nuvola_apps_edu_miscellaneous.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Nuvola_apps_edu_miscellaneous.svg/64px-Nuvola_apps_edu_miscellaneous.svg.png 2x" data-file-width="128" data-file-height="128" /></td> 
   <td style="background-color:#f0fff0; border-left: 4px solid green; padding-left: 6px;"><span id="code-section-26"><b>Code section 6.26: Chaining-aware constructor.</b></span> 
    <div class="mw-highlight mw-content-ltr" dir="ltr"> 
     <pre>
<span class="lineno">1 </span><span class="k">try</span> <span class="o">{</span>
<span class="lineno">2 </span>    <span class="n">lowLevelOp</span><span class="o">();</span>
<span class="lineno">3 </span><span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="n">LowLevelException</span> <span class="n">le</span><span class="o">)</span> <span class="o">{</span>
<span class="lineno">4 </span><span class="hll">    <span class="k">throw</span> <span class="k">new</span> <span class="n">HighLevelException</span><span class="o">(</span><span class="n">le</span><span class="o">);</span>
</span><span class="lineno">5 </span><span class="o">}</span>
</pre> 
    </div> </td> 
  </tr> 
 </tbody> 
</table> 
<p>Because the initCause method is public, it allows a cause to be associated with any throwable, even a "legacy throwable" whose implementation predates the addition of the exception chaining mechanism to Throwable. For example:</p> 
<table style="padding:2px; margin:2px;"> 
 <tbody> 
  <tr valign="top"> 
   <td style="width:32px;"><img alt="Example" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Nuvola_apps_edu_miscellaneous.svg/32px-Nuvola_apps_edu_miscellaneous.svg.png" title="Example" width="32" height="32" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Nuvola_apps_edu_miscellaneous.svg/48px-Nuvola_apps_edu_miscellaneous.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Nuvola_apps_edu_miscellaneous.svg/64px-Nuvola_apps_edu_miscellaneous.svg.png 2x" data-file-width="128" data-file-height="128" /></td> 
   <td style="background-color:#f0fff0; border-left: 4px solid green; padding-left: 6px;"><span id="code-section-27"><b>Code section 6.27: Legacy constructor.</b></span> 
    <div class="mw-highlight mw-content-ltr" dir="ltr"> 
     <pre>
<span class="lineno">1 </span><span class="k">try</span> <span class="o">{</span>
<span class="lineno">2 </span>    <span class="n">lowLevelOp</span><span class="o">();</span>
<span class="lineno">3 </span><span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="n">LowLevelException</span> <span class="n">le</span><span class="o">)</span> <span class="o">{</span>
<span class="lineno">4 </span><span class="hll">    <span class="k">throw</span> <span class="o">(</span><span class="n">HighLevelException</span><span class="o">)</span> <span class="k">new</span> <span class="n">HighLevelException</span><span class="o">().</span><span class="na">initCause</span><span class="o">(</span><span class="n">le</span><span class="o">);</span>
</span><span class="lineno">5 </span><span class="o">}</span>
</pre> 
    </div> </td> 
  </tr> 
 </tbody> 
</table> 
<p>Further, as of release 1.4, many general purpose Throwable classes (for example <code>Exception</code>, <code>RuntimeException</code>, <code>Error</code>) have been retrofitted with constructors that take a cause. This was not strictly necessary, due to the existence of the <code>initCause</code> method, but it is more convenient and expressive to delegate to a constructor that takes a cause.</p> 
<p>By convention, class <code>Throwable</code> and its subclasses have two constructors, one that takes no arguments and one that takes a String argument that can be used to produce a detail message. Further, those subclasses that might likely have a cause associated with them should have two more constructors, one that takes a <code>Throwable</code> (the cause), and one that takes a String (the detail message) and a <code>Throwable</code> (the cause).</p>
